# Generated by Django 4.2 on 2025-10-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombrecompleto', models.CharField(max_length=20)),
                ('carrera', models.CharField(max_length=25)),
            ],
        ),
    ]
